### ISSUE TITLE
Regarding Registration of S16 Rd2l

### ISSUE THREAD

**Issue by prakhar3949** [redditdota2league/server#125]
Cant register for S16 as Dota2 Client down. "**The bot that attempted to fetch your MMR is down.
Please contact an admin.**"
<img width="905" alt="screenshot 2018-12-25 at 4 32 20 am" src="https://user-images.githubusercontent.com/46113920/50407502-26780c00-07fe-11e9-8cc0-843d6cdc4f09.png">

**Comment by dambrisco** [comment]
This is usually an issue on Valve's end that resolves itself eventually. I'm unavailable for the next 24 hours or so due to Christmas events so I'll check back in around then if the issue is ongoing.
