### ISSUE TITLE
random internal server error on some user submissions

### ISSUE THREAD

**Issue by kabobrocks** [redditdota2league/server#131]
I haven't been able to replicate it, but it happens. Nothing odd on their forms either

**Comment by dambrisco** [comment]
@kabobrocks Do we have any screenshots of data that triggers the issue? If not I can try fuzzing it.

**Comment by kabobrocks** [comment]
nothing out of the ordinary:

https://imgur.com/4UCajPr
https://cdn.discordapp.com/attachments/159369184428556288/530343061503475712/Screenshot_20190103-121352_Chrome.jpg

**Comment by dambrisco** [comment]
Could it be the previous season rank not being available?

**Comment by kabobrocks** [comment]
nope, I put in code to force it to be 0 if it was blank for us. Also, the submission doesn't even do anything with previous rank that I recell

**Comment by kabobrocks** [comment]
clsoing this and remaking if something new comes up
