### ISSUE TITLE
Clicking on "Playoffs" and/or "Bracket" causes other buttons to disappear

### ISSUE THREAD

**Issue by ocket8888** [redditdota2league/server#160]
Not sure if this is done because of a data retention policy (in which case disregard this) but when clicking on either "Playoffs" or "Bracket" from a Division view, all the other buttons e.g. "Players" disappear.

**Comment by tristan-gill** [comment]
bracket is division independent, while the rest of the tabs depend on the division they are in.
For instance EST MON and EST SUN both see the same `Bracket` button that takes them to the same place. Once on the bracket page its more difficult to tell which division the `Players` tab should reference.

**Comment by ocket8888** [comment]
Ah, so playoffs are cross-division, then?

**Comment by kabobrocks** [comment]
correct

**Comment by ocket8888** [comment]
Then this isn't a real issue
