### ISSUE TITLE
Add scrim week support

### ISSUE THREAD

**Issue by dambrisco** [redditdota2league/server#41]
@kabobrocks so I just realized we've actually got no way to generate a set of random matchups. We'll need to special case "Week 0" or something and use a deterministically generated seed similar to what's used in swiss-pairings to generate team seeds or something.

Maybe we can just sort the team ids? Need to look at how random those are.

**Comment by dambrisco** [comment]
Yeah - those, series, and possibly a couple other things still remain from the division switchover. I was planning to tackle those this weekend, but if you beat me to it I won't mind.

**Comment by kabobrocks** [comment]
PR up shortly

**Comment by kabobrocks** [comment]
#42
