### ISSUE TITLE
Change default division page

### ISSUE THREAD

**Issue by aeosynth** [redditdota2league/server#76]
With the new navigation, the default division page is mostly redundant, and we could make a different page such as standings the default. The 'useful information' could be in a separate page, folded into another page, or embedded into each page.

**Comment by kabobrocks** [comment]
If anything I think I would want to add a new "Division Hub" button to the new navigation. I have some plans that I would like to work on to make the Division Hub unique (Hall of Fame, Banners, etc) and worthy of being the default page

**Comment by aeosynth** [comment]
can we change the default page for now, until the new 'division hub' page exists?
