### ISSUE TITLE
List opponents under one column in series table on individual team pages

### ISSUE THREAD

**Issue by devilesk** [redditdota2league/server#77]
On the individual team pages ([example](https://rd2l.gg/seasons/SylVxBloM/divisions/Hkhg_uesz/teams/Bk6Zxi0Tf)) in the series table put all the opponents a team has played under one column instead of separating them by home and away team.

The home/away distinction is unnecessary and just makes it harder to read the table and see all the opponents because you have to go back and forth between two columns. Likewise, the home/away team points should just be own points vs opponent points so you can easily see the outcomes by looking at a single column and you can just sum the column to get total wins or losses.

**Comment by kabobrocks** [comment]
#79
